spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mp?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: mp
    password: mp
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

storage:
  path: /Users/jjh/project/file/mp